define({
  "root": {
    "app": {
      "areYouSure": "Are you sure",
      "geoloaction": "Geolocation",
      "task":"Task",
      "template": "Template",
      "noData": "No data available",
      "inventoryFilter":"Inventory Filter",
      "moreInfo":"More Info",
      "ok":"Ok",
      "barChart": "Bar Chart",
      "powerBI": "Power BI",
      "pieChart": "Pie Chart",
      "bubbleChart": "Bubble Chart",
      "productDistribution": "Product Distribution",
      "selectDate": "Select Date Range",
      "reset": "Reset",
      "submitButton": "Submit",
      "selectStartDate": "Start date",
      "selectEndDate": "End date",
      "actions": "Actions",
      "analytics": "Analytics",
      "invalidCredentials": "Invalid credentials",
      "completed": "Completed",
      "submit": "SUBMIT",
      "back": "No, go back",
      "surveyNotFound": "Survey not found",
      "surveyList": "Survey List",
      "week": "Week",
      "series": "Series {0}",
      "yes": "Yes",
      "no": "No",
      "assets": "Assets",
      "order": "Order",
      "serviceRequest": "Service Request",
      "initiatives": "Initiatives",
      "Title": "Title",
      "cancel": "Cancel",
      "close": "Close",
      "filter": "Filter",
      "success": "Success",
      "active": "ACTIVE",
      "edit": "Edit",
      "delete": "Delete",
      "date": "Date",
      "cancel": "Cancel",
      "confirm":"Confirm",
      "contacts": "Contacts",
      "save": "Save",
      "selectType": "Select Type",
      "offlineMsg": "Check your network connection",
      "onlineMsg": "Connected to network",
      "viewAll": "View all",
      "active": "Active",
      "inActive": "inactive",
      "closed": "Closed",
      "today": "Today",
      "search": "Search",
      "add": "Add",
      "new": "New",
      "current": "Current",
      "available": "Available",
      "start": "Start",
      "end": "End",
      "type": "Type",
      "private": "Private",
      "author": "Author",
      "note": "Note",
      "primary": "Primary",
      "by": "by",
      "overView": "Overview",
      "target": "Target",
      "forecast": "Forecast",
      "class": "Class",
      "status": "Status",
      "address": "Address",
      "code": "Code",
      "name": "Name",
      "unit": "Unit",
      "select": "Select",
      "searchOnline": "Search Online",
      "id": "ID",
      "inventoryAudit": "Inventory Audit",
      "priceAudit": "Price Audit",
      "created": "Created",
      "files": "Files",
      "dashboard": "Dashboard",
      "accounts": "Accounts",
      "accountDetails": "Account Details",
      "route": " Route",
      "visit": "Visit",
      "surveys": "Surveys",
      "survey": "Survey",
      "notes": "Notes",
      "newNote": "New Note",
      "surveyDetail": "Survey Detail",
      "account": "Account",
      "logout": "Logout",
      "logoutTitle": "Are you sure you want to logout?",
      "done": "Done",
      "accountNotes": "Account Notes",
      "visitNotes": "Visit Notes",
      "deleteConfirm": "Are you sure you want to delete record?",
      "attachments": "Attachments",
      "addNew": "Add New",
      "syncData": "Synchronize data",
      "manager": "Manager",
      "entity":{
        "accounts": "Account",
        "account_notes": "Note",
        "visit_notes": "Note",
        "account_addresses": "Address",
        "account_attachments": "Account Attachment",
        "audit_details": "Audit Details",
        "contacts": "Contacts",
        "resource": "Resource",
        "routes": "Routes",
        "store_visit_tasks": "Visit Tasks",
        "visit_attachments": "Visit Attachments",
        "visits": "Visit",
        "audit_history": "Audit History"
      },  
  
      "noVisits": "No visit available",
      "footer": {
        "dashboard": "Home",
        "myDay": "My Day",
        "followup": "Follow Up",
        "visit": "Visit",
        "details": "Details",
        "account": "Accounts"
      },
      "weekDays": {
        "monday": "Monday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday",
        "thursday": "Thursday",
        "friday": "Friday",
        "saturday": "Saturday"
      },
      "alertTxt": {
        "noteTxt1": 'Account A1234 with settlements due',
        "noteTxt2": 'Account B3456 Initiative rejected',
        "noteTxt3": 'Account C5678 Initiative approved. Pending signature.'
      },
      "error": {
        "unknown": {
          "title": "Error",
          "message": "There was an error. please try again later."
        },
        "sync": {
          "title": "Sync",
          "message": "Few records are yet to push for other user"
        }
      }
    },
    "createVisit":{
      "apply":"Apply",
      "subject":"Subject",
      "Visit_Type":"Visit Type",
      "Select_Visit_type":"Select Visit type",
      "Visit_Template":"Visit Template",
      "Select_Visit_template":"Select Visit template",
      "No_Template_Selected":"No Template Selected",
      "cancelVistCnfrm": "Do you want to cancel creation of the visit?",
      "Visit_wont_save":"Visit will not be saved",
      "create_visit_cnfrm":"Do you want to create the visit?",
      "Yes_cancel":"Yes, cancel",
      "No_go_back":"No, go back",
      "new_visit": "New Visit",
      "noTemplateSave" : "Are you sure you want to create a visit with out a task",
      "selectAccount": "Account Name is required",
      "enterSubject": "Subject is required",
      "templateDetails":"Template Details",
    },
    "survey":{
      "question": "Question",
      "previous": "Previous",
      "nextQuestion": "Next Question",
    },
    "account360": {
      "noPrevoiusVisit":"No previous visits available",
      "marketShare": "Market Share",
      "nextVisit": "Next visit",
      "visitHistory": "Visit History",
      "visitHistoryDet": "Visits’ history",
      "surveys": "Surveys",
      "visitsCompleted": "visits completed",
      "visit": "Visit",
      "lastVisit": "Last visit",
      "noFollowupActions": "You have no pending follow up actions on this account",
      "activeFollowupActions": "You have active follow up actions on this account",
      "completedMandatoryTasks": "mandatory tasks",
      "mandatoryTasks": "mandatory tasks",
      "goToVisit": "go to visit",
      "noVisitsCompleted": "No completed visits",
      "completedVisits": "Completed visits",
      "addVisit": "ADD VISIT",
      "conductedBy": "Conducted By",
      "completedActivities": "Completed Activities",
      "notScheduled": "No planned visit",
      "addVisit": "add a visit",
      "currentVisit": "Current visit",
      "noPlannedVisitsForToday":"No visits planned for today",
      "addVisit":"Add Visit"
    },
    "sync": {
      "title": "Sync",
      "message": "Few records are yet to push for other user",
      "error": {
        "create": "Something went wrong unable to Sync created",
        "edit": "Something went wrong unable to Sync Edit",
        "delete": "Something went wrong unable to Sync Delete",
        "syndown": "Error in Sync Down",
        "batch": "batch operation failled"
      },
      "entity": {
        "note": "Note",
        "address": "Address",
        "attachment": "Attachment",
        "visit": "Visit"
      },
      "info": {
        "yettoPush": "Few records are yet to push for other user"
      },
      "visitWarning": {
        "yetToComplete": "you have pending visit, please checkout of the visit to sync new data"
      }
    },
    "login": {
      "username": "Username",
      "password": "Password",
      "login": "Login",
      "error": {
        "authentication": {
          "title": "Error",
          "message": "Invalid Credentials, please try again."
        },
        "unknown": {
          "title": "Error",
          "message": "There was an error. please try again later."
        },
        "sync": {
          "title": "Sync",
          "message": "Few records are yet to push for other user"
        }
      }
    },
    "account-details": {
      "segmentation": "Segmentation",
      "visitHistory": "Visit History",
      "primaryContact": "Primary Contact",
      "secondaryContact": "Secondary Contact",
      "accountInformation": "Account Information",
      "retailInitiatives": "Retail Initiatives",
      "openingHours": "Opening Hours",
      "notes": "Notes",
      "attachments": "Attachments",
      "POSM": "POSM",
      "addresses": "Addresses",
      "contacts": "Contacts",
      "orderOrInvoiceHistory": "Order/Invoice History",
      "objectiveKPIs": "Objective KPIs",
      "wholeSalers": "Wholesalers",
      "legalEntities": "Legal Entities",
      "merchandisingUnits": "Merchandising Units",
      "inventoryAssortments": "Inventory Assortments",
      "serviceRequest": "Service Request",
      "assets": "Assets",
      "accountInformationDet": {
        "parentAccount": "Parent Account",
        "channel": "Channel",
        "phoneNumber": "Phone Number",
        "emailAddress": "Email Address",
        "territoryOwner": "Territory Owner",
        "lastVisit": "Last Visit",
        "lastPlannedVisit": "Last Planned Visit",
        "visitRequired": "Visit Required",
        "visitFrequency": "Visit Frequency",
        "segmentation": "Segmentation",
        "additionalInformation": "Additional Information",
        "segmentationDet": {
          "segment": "Segment",
          "brandFocus": "Brand Focus",
          "tradeSegment":"Trade Segment",
          "consumerSegmentPr":"Consumer Segment Pr",
          "consumerSegmentSec":"Consumer Segment Sec"
        },
        "additionalInformationDet": {
          "visitRequireInfo":"This change will make visit mandatory for account",
          "distributorWH":"Distributor WH Level1",
          "accountCode":"Account Code",
          "globalChannel":"Global Channel",
          "accountType":"Account Type",
          "currencyCode":"Currency Code",
          "accountOwnerName":"Account Owner",
          "marketChannel":"Market Channel",
          "inactivatedSince":"Inactivated Since",
          "assortment": "Assortment",
          "priority": "Priority",
          "customerSince": "Customer Since",
          "integrationCode": "Integration Code",
          "copyRestricted": "Copy Restricted",
          "originalAccount": "Original Account",
          "activatedState": "Activated State",
          "reasonsForInactivation": "Reasons For Inactivation",
          "marketAttribute1": "Market Attribute 1",
      
        }
      },
      "retailInitiativesDept": {
        "initiatives": "Initiatives",
        "negotiationEnd": "Negotiation End",
        "contract": "Contract"
      },
      "openingHoursDept": {
        "preferredVisitDay": "Preferred Visit Day",
        "avoidDay": "Avoid Day"
      },
      "attachmentsDept": {
        "backOfficeTeam": "BACK OFFICE & TEAM",
        "myAttachments": "MY ATTACHMENTS"
      },
      "addressesDept": {
        "billTo": "Bill to",
        "shipTo": "Ship to"
      },
      "wholeSalersDept": {
        "viewPriceBook": "View Price Book",
        "makePrimary": "Make Primary"
      },
      "merchandisingUnitsDept": {
        "productPosition": "Product Position",
        "installationDate": "Installation Date",
        "subtype": "Subtype"
      }
    },

    "dashboard": {
      "welcome": "Good Morning",
      "welcomemorning": "Good Morning",
      "welcomeafternoon": "Good Afternoon",
      "welcomeevening": "Good Evening",
      "contacts": "Contacts",
      "alerts": "Focus Group",
      "accounts": "Accounts",
      "completed": "Completed",
      "analytics": "Territory SOM (RMC)",
      "myroute": "My Day (Route)",
      "active": "Active",
      "lastsync": "Last synchronized:",
      "visitscompleted": "visits completed",
      "contactstext": "{0} Contacts",
      "todaysSchedule": "Today's Schedule",
      "nextAppointment": "Next appointment",
      "premium": "Premium",
      "noFollowupActions": "You have no pending follow up actions",
      "activeFollowupActions": "You have active follow up actions"
    },
    "visit": {
      "account": "Account",
      "visit": "Visit",
      "visitActivityTitle": "Visit Activities"
    },
    "visitDetails": {
      "surveyMessage":"You have survey task associated with this visit, this  will add template to the survey",
     "noSurveyTemplate":"No survey template available",
      "isAdded": "is added to visit",
      "addToVisit":"add to visit",
      "addedToVisit":"added to visit",
      "adhocTaskAddConfirm":"Do You want to add the task to the visit?",
      "selectActivity":"Select Activity",
      "wantToCheckout": "Do you want to check-out?",
      "tasksPending": "There are still tasks pending in this visit",
      "pendingActivities": "Pending activities",
      "reasonForCheckout": "Indicate a reason for checking-out",
      "goBackToVisit": "Go back to visit",
      "pleaseSelectReason": "Please select a reason for checkout for all the pending tasks",
      "pendingVisits": "you have pending visits",
      "checkoutPreviousVisit": "please checkout of the previous visit before checking-in to this visit",
      "areYouSureToCheckin": "Are you sure want to check-in?",
      "areYouSureToCheckout": "Assuming tasks has completed. Do you want to checkout ?",
      "giveValidReason": "please give a valid reason",
      "visitActivites": "Visit Activities",
      "cycleActivites": "Cycle Activities",
      "noTasks": "No Tasks Assigned",
      "oneSuerveyTemplateAssociated": "There is only one survey template associated with this visit",
      "accountTextSurveyTemplate":"There is no account servey template associated to this visit",
      "visitTextSurveyTemplate": "There is no visit servey template associated to this visit",
      "addSurveyTemplate": "Survey has not associated with this task. Please select one of the below surveys to execute.",
      "execute": {
        "checkin": "Check In",
        "checkout": "Check Out"
      },
      "status": {
        "pending": "Pending",
        "notStarted": "Not Started",
        "inprogress": "In Progress",
        "completed": "Completed",
        "newStatus": "Not Started"
      },
      "menu": {
        "selectothervisit": "Select other visit",
        "notes": "Notes",
        "attachments": "Attachments",
        "followup": "Follow-Up Actions",
        "newactivity": "New Activity",
        "reschedule": "Reschedule",
        "cancelvisit": "Cancel Visit",
        "addAdhocTask": "Add Ad-Hoc Task"
      },
      "options": "Options"
    },
    "accounts": {
      "next": "Next",
      "last": "Last",
      "accountName": "Account Name",
      "visitDates": "Visit Dates",
      "activeAccounts": "{0} Active Accounts",
      "inActiveAccounts": "{0} Inactive Accounts",
      "candidateAccounts": "{0} Candidate Accounts",
      "allCount": "{0} Accounts",
      "accountsCount": "{0} Active and {1} Inactive Accounts",
      "accountNumber": "Account Number"
    },
    "jti-task-card": {
      "lastupdated": "Last Check: ",
      "never": "Pending",
      "today": "Today",
      "removeconfirm": "Are you sure you want to remove the task '{0}' from the visit?",
      "dialogtitle": "Remove Task from visit"
    },
    "accountNotes": {
      "next": "Next",
      "last": "Last",
      "type": "Type",
      "author": "Author",
      "private": "Private"
    },
    "notesAdd": {
      "addNote": "Add Note",
      "newNote": "New Note",
      "updateNote": "Update Note",
      "storetype": "Select note type",
      "makePrivate": "Make private",
      "yourNote": "Your note",
      "createdNote": "Created Note",
      "isEdited": "is edited",
      "noteDelteSuccessMsg": "Note Deleted",
      "placeholder": "Search Notes",
      "validation": {
        "requiredStoretype": {
          "messageSummary": "Value is required.",
          "messageDetail": "You must select a store type."
        },
        "requiredNoteTxt": {
          "messageSummary": "Value is required.",
          "messageDetail": "You must enter some note."
        },
        "length": {
          "minLengthSummary": "There are too few characters.",
          "minLengthDetail": "Enter {0} or more characters, not fewer."
        }
      }
    },
    "addressList": {
      "pageTitle": "Addresses",
      "primary": "Primary",
      "question": "Are you sure to delete the address?",
      "selectString": "Select the new Primary Address",
      "isDeleted": "is deleted",
      "isCreated": "is created",
      "isUpdated": "is updated",
      "deleteConfrimMsg": "Are you sure you want to delete this address?",
      "addAddress": "New Address",
      "editAddress":"Update Address",
      "secoToPrimaryAddressConfmMsg": "Are you sure you want to make this address as Primary?",
      "searchOnMapText":"Show on the map",
      "setPrimaryAddress":"Set as Primary Address",
      "addInfo":"Additional Information",
      "confirm":"Confirm",
      "deleteInfo":"You're about to delete primary address.",
      "delteSubinfo":"Choose the new primary address for this account and confirm to proceed"
    },
    "route":{
      "visitStatus":"Visit Status",
      "rechedule":"Rechedule",
      "filters":"Filters",
      "clearFilter":"Clear All",
      "applyFilter":"Apply Filter", 
      "apply":"Apply",
      "visitsCompleted":"visits completed",
      "selectDate":"Select a date",
      "offlineMsg":"Map can't be loaded in the offline mode",
      "addNew":"Add New",
      "newVisit": "New Visit",
      "disabledLocation": "Please enable location to load the map"
    },
    "attachments":{
      "notifications":{
        "IMAGE": {
          "successMessage":"Successfully uploaded.",
          "invalidSize": "Invalid file size",
          "sizeLimit":"File size should be less than 20MB.",
          "errormessage":"Something went wrong while uploading IMAGE.",
        },
        "PDF":{
          "successMessage":"Successfully uploaded.",
          "invalidSize": "Invalid file size",
          "sizeLimit":"File size should be less than 20MB.",
          "errormessage":"Something went wrong while uploading PDF.",
        },
        "genericerrormsg":"Something went wrong while uploading File.",
        "attach_file_err": "Please attach file",
        "invalid_doc" : "Unable to upload selected format",
        "invalid_doc_title": "Invalid Document"
      },
      "imageOption": "Take a photo",
      "galleryOptions": "Use a photo from gallery",
      "pdfOption": "Upload Pdf",
      "docOption": "Upload Document",
      "delete": "Delete",
      "edit":"Edit",
      "share": "Share",
      "addNew": "Add New",
      "change": "Change",
      "addAttach": "Attachment",
      "cancelAlert": "Do you want to cancel the attachment creation?",
      "calcelInfo": "File won't be saved",
      "back": "No, go back",
      "caneclForm": "Yes, cancel",
      "fileLabel": "File Name"
    },
    "sideBar":{
      "notifications":"Notifications",
      "userGuide":"Users Guide"
    },
    "inventoryAudit": {
      "viewDetails": "view details",
      "productCode": "Product Code",
      "searchProduct": "Search for product name",
      "available": "Available",
      "outOfStock": "Out of stock",
      "nonDistributed": "Non distributed",
      "facings": "Facings",
      "sellingPrice": "Selling Price",
      "unavailabilityReason": "Please select the non-availability reason",
      "unavailabilityReasonSubText": "This is mandatory field for non available products",
      "flag":"Flag",
      "productDetails": "Product details",  
      "keyQuestions": "Key questions",
      "availability": "Availability",
      "brandName": "Brand",
      "manufacturer": "Sales Organization",
      "brandfamily": "Brand Family",
      "producttype": "Product Type",
      "filters": "Filters",
      "areYouSure":"Are you sure you want to complete the task?"
    },
    "planogram": {
      "title": "Planogram",
      "fileView": "File Preview"
    },
    "contacts": {
      "primary": "Primary",
      "phoneLabel": "Telephone",
      "prefix": "Prefix",
      "firstName": "First Name",
      "lastName": "Last Name",
      "role": "Role",
      "email": "Email",
      "preferEmail": "e-mail",
      "preferMethodContact": "Preferred method of contact",
      "contactStatus": "Contact Status",
      "contactTypePlaceHolder": "Select Contact Type",
      "contactRolePlaceHolder": "Select Contact Role",
      "activeStatusLabel": "Active",
      "emailPlaceHolder": "email.address@email.com",
      "messages":{
        "createSuccess": "Contact Created Successfully."
      }
    },
    "surveys":{
      "openSurvey":"Open survey",
      "lastPerformed":"Last Performed: ",
      "preview":"Preview",
      "question":"Question",
      "summary":"Summary",
      "collectSignature":"Collect Signature",
      "submitedSurvey": "Submitted Survey" ,
      "commentErrorMessage":"Please add Comments as you have selected Other as option"
    }
  },
  "es": true,
  "ro": true,
  "it": true
});